# Usar la imagen base de Nginx
FROM nginx:latest

# Copiar el archivo de configuración de Nginx al contenedor
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

# Exponer el puerto 80
EXPOSE 80
