version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3000:5173"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    command: >
      sh -c "npm install &&
             npm run dev -- --host"
